### ISSUE TITLE
Import doublecloud_transfer_endpoint to terraform state leads to nil pointer

### ISSUE THREAD

**Issue by clumpytuna** [doublecloud/terraform-provider-doublecloud#73]
Imports `doublecloud_transfer_endpoint` leads to an error:
 
terraform body: 

```
import {
  to = doublecloud_transfer_endpoint.name
  id = <id>
}
resource "doublecloud_transfer_endpoint" "name" {
  name       = "name"
  project_id = "project_id"
  settings {
    mysql_source {
      database = "di-mysql-main"
      user     = "user"
      password = "password"
      connection {
        on_premise {
          hosts = ["main-example.eu-west-1.rds.amazonaws.com"]
          port  = 3306
        }
      }
      include_tables_regex = []
      exclude_tables_regex = []
      service_database     = ""
      timezone             = "Africa/Johannesburg"
    }
  }
}
```

Seems like default parameters may be filled with nils by default that leads to the problem.

logs: [doublecloud.log](https://github.com/doublecloud/terraform-provider-doublecloud/files/14980378/doublecloud.log)

can be related to this: https://github.com/doublecloud/terraform-provider-doublecloud/blob/27f0583bc54ad3fb97db8f5b3e66adf00923a2ed/internal/provider/transfer_endpoint_mysql.go#L367

**Comment by epikhinm** [comment]
Hi @clumpytuna, fixed here https://github.com/doublecloud/terraform-provider-doublecloud/pull/77

Check out [v0.1.14](https://github.com/doublecloud/terraform-provider-doublecloud/releases/tag/v0.1.14)
