### ISSUE TITLE
Support for Allow List in Clickhouse cluster resource

### ISSUE THREAD

**Issue by matan-cohen** [doublecloud/terraform-provider-doublecloud#9]
Is there any roadmap regarding providing support to control the 'Allow List' of ip cidr by the Clickhouse resource?

**Comment by Gaploid** [comment]
Hi @matan-cohen, yep its already in work and its coming in next 1-2 weeks.

**Comment by epikhinm** [comment]
@matan-cohen Hi.
We've implemented it.
You can check it since `v0.1.5`
https://registry.terraform.io/providers/doublecloud/doublecloud/latest/docs/resources/clickhouse_cluster#nestedblock--access
